### Natural Language Processing I

**OBJECTIVES**

- Use text in a predictive model
- Build sentiment analysis model
- Package model in Flask application

In [44]:
import pandas as pd

train = pd.read_csv('data/clothing_reviews.csv')

In [45]:
train.head()

Unnamed: 0  Clothing ID  Age                    Title  \
0           0          767   33                      NaN   
1           1         1080   34                      NaN   
2           2         1077   60  Some major design flaws   
3           3         1049   50         My favorite buy!   
4           4          847   47         Flattering shirt   

                                         Review Text  Rating  Recommended IND  \
0  Absolutely wonderful - silky and sexy and comf...       4                1   
1  Love this dress!  it's sooo pretty.  i happene...       5                1   
2  I had such high hopes for this dress and reall...       3                0   
3  I love, love, love this jumpsuit. it's fun, fl...       5                1   
4  This shirt is very flattering to all due to th...       5                1   

   Positive Feedback Count   Division Name Department Name Class Name  
0                        0       Initmates        Intimate  Intimates  
1                        4         General         Dresses    Dresses  
2                        0         General         Dresses    Dresses  
3                        0  General Petite         Bottoms      Pants  
4                        6         General            Tops    Blouses

### Vectorize the Text

In [23]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

from sklearn.pipeline import make_pipeline

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [24]:
train.shape

(6917, 2)

In [68]:
cvect = CountVectorizer(stop_words='english', max_features=500)

cvect.fit(train.text)

import numpy as np
from sklearn.model_selection import train_test_split

train = train.dropna(subset = ['Review Text', 'Rating'])

X = train['Review Text']
y = np.where(train['Rating'] > 3, 1, 0)

X_train, X_test, y_train, y_test = train_test_split(X, y)

from sklearn.preprocessing import StandardScaler

lgr_pipe = make_pipeline(CountVectorizer(max_features = 500), StandardScaler(with_mean=False), LogisticRegression())

lgr_pipe.fit(X_train, y_train)

In [91]:
from joblib import dump, load
dump(lgr_pipe, 'lgr_pipe.joblib') 

['lgr_pipe.joblib']

In [69]:
lgr_pipe.score(X_test, y_test)

0.8625684508037449

In [70]:
pd.value_counts(y_test, normalize = True)

1    0.777778
0    0.222222
dtype: float64

In [82]:
knn_pipe = make_pipeline(CountVectorizer(stop_words='english', max_features = 1000), 
                         StandardScaler(with_mean=False), KNeighborsClassifier())
dtree_pipe = make_pipeline(CountVectorizer(stop_words='english', max_features = 1000),
                           DecisionTreeClassifier())
rforest_pipe = make_pipeline(CountVectorizer(stop_words='english', max_features = 1000), 
                             RandomForestClassifier())

In [83]:
knn_pipe.fit(X_train, y_train)
knn_pipe.score(X_test, y_test)

0.7929694400282635

In [84]:
dtree_pipe.fit(X_train, y_train)
dtree_pipe.score(X_test, y_test)

0.7823706059000176

In [85]:
rforest_pipe.fit(X_train, y_train)
rforest_pipe.score(X_test, y_test)

0.8496732026143791

In [86]:
test_point = np.array(["I really really loved these sandals, they got so many complements and I looked great!"])

In [87]:
rforest_pipe.predict(test_point)

array([1])

In [88]:
test_point = np.array(["I really really hated these leggings.  They made me look gross, and my friends laughed at me!"])

In [89]:
rforest_pipe.predict(test_point)

array([1])

In [90]:
lgr_pipe.predict(test_point)

array([1])